import { type Module, inject, IndentationAwareLexer, IndentationAwareTokenBuilder } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { CardDslGeneratedModule, CardDslGeneratedSharedModule } from './generated/module.js';
import { CardDslValidator, registerValidationChecks } from './card-dsl-validator.js';
import { CardDslScopeProvider } from './card-dsl-scope.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type CardDslAddedServices = {
    validation: {
        CardDslValidator: CardDslValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type CardDslServices = LangiumServices & CardDslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const CardDslModule: Module<CardDslServices, PartialLangiumServices & CardDslAddedServices> = {
    validation: {
        CardDslValidator: () => new CardDslValidator()
    },
    
    references: {
        ScopeProvider: (services) => new CardDslScopeProvider(services)
    },
    
    parser: {
        TokenBuilder: () => new IndentationAwareTokenBuilder({
            indentTokenName: 'INDENT',
            dedentTokenName: 'DEDENT',
            whitespaceTokenName: 'WS',
            ignoreIndentationDelimiters: [
                ['[', ']'],
                ['(', ')']
            ]
        }),
        Lexer: (services) => new IndentationAwareLexer(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createCardDslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    CardDsl: CardDslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CardDslGeneratedSharedModule
    );
    const CardDsl = inject(
        createDefaultModule({ shared }),
        CardDslGeneratedModule,
        CardDslModule
    );
    shared.ServiceRegistry.register(CardDsl);
    registerValidationChecks(CardDsl);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, CardDsl };
}
